### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by jasonm** [daily-co/synthetic-network#4]
# Feature request

Perhaps more a question or discussion than feature request, but: do you have any experience running this on ARM platforms e.g. Apple M1 or AWS Graviton?

Looks like MediaSoup may support ARM [ref1](https://github.com/versatica/mediasoup/issues/321) [ref2](https://mediasoup.discourse.group/t/mediasoup-v2-compile-error-unrecognised-cmd-line-option-m64/134/7).

The asm code in `rush` referenced in #2 / #3 indeed comes with both x86_64 and aarch64 targets.

# Why you need this

I primarily develop on an M1 Mac. This is very much in the "nice-to-have" territory, but I am curious if others are successfully using this on ARM.

# Alternatives you've considered

The main issues I encountered with ARM, and workarounds I tried, in case it's useful:

The `chrome` image installs `google-chrome-stable` on Debian, but [Google only provides Chrome for Linux amd64](https://askubuntu.com/questions/1383789/install-chrome-on-ubuntu-debian-with-arm64). Docker for Mac provides emulation via `qemu` (support for which [should be regarded as "best effort" only](https://docs.docker.com/desktop/mac/apple-silicon/)). For me, amd64 (x86) Chrome in Docker (via `make run-chrome`) failed to launch with [this error](https://stackoverflow.com/questions/70069412/error-installing-chrome-on-aws-ec2-linux-instance-scaling-cur-freq-scaling-ma/70113555#70113555).

I was not successful in finding an older version of Chrome that successfully launched via apt or deb for Debian 9 (per this repo's Dockerfile `FROM node:12.20.2`) or Debian 11 (the newest stable version; easy to update by changing this repo's Dockerfile to use `FROM node:12-bullseye`).

I also tried various versions of Chromium under arm64, but was not successful.

I ended up running it successfully on an x86 machine, but thought I'd share notes in case this is useful 😄

**Comment by kwindla** [comment]
Just wanted to close the loop and say that we've merged two patches that, for us, together provide working ARM support. Thanks for your PR, here! Let us know if you still have any issues on `main`.
